"""Generate every numerical manuscript input from completed, matched study outputs."""
from __future__ import annotations
import argparse,json,re,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/'src'))
import numpy as np
import pandas as pd
from psl_flexibility.evaluation import cluster_bootstrap,sha256_file

STUDY=ROOT/'results/study';PAPER=ROOT/'paper'
LABELS={'graph':'Graph geometry','native0':'Legacy graph spectra','graph+native0':'Graph + legacy spectra',
    'center0':'Center-zero spectra','graph+identity0':'Graph + identity sheaf',
    'graph+geometric0':'Graph + geometric sheaf','graph+center0':'Graph + center-zero sheaf'}
NUMBERS={};SOURCES={};VALIDATED_RUNS=set()

def source(path):
    digest=sha256_file(path)
    SOURCES[str(path.relative_to(ROOT)).replace('\\','/')]=digest
    return digest

def read(run,name):
    cfg=json.loads((STUDY/run/'evaluation_config.json').read_text())
    if not cfg['complete']:raise ValueError(f'Incomplete result {run}')
    if run not in VALIDATED_RUNS:
        dataset=json.loads((STUDY/'dataset/dataset_config.json').read_text())
        if cfg['cohort']!='all' or cfg['n_proteins']!=dataset['n_proteins'] or cfg['n_residues']!=dataset['n_residues']:
            raise ValueError(f'{run}: reporting requires the exact full audited cohort')
        for item,digest in cfg['manifest_sha256'].items():
            if source(STUDY/'dataset'/item)!=digest:raise ValueError(f'{run}: stale {item}')
        cols=['protein_id','cluster_id','protein_fold','cluster_fold']
        expected=pd.read_csv(STUDY/'dataset/folds.csv')[cols].sort_values('protein_id').reset_index(drop=True)
        actual=pd.read_csv(STUDY/run/'evaluation_fold_manifest.csv')[cols].sort_values('protein_id').reset_index(drop=True)
        if not actual.equals(expected):raise ValueError(f'{run}: cohort, clusters or folds differ')
        source(STUDY/run/'evaluation_config.json');source(STUDY/run/'evaluation_fold_manifest.csv')
        VALIDATED_RUNS.add(run)
    file=STUDY/run/name
    digest=sha256_file(file)
    if name in cfg['outputs_sha256'] and digest!=cfg['outputs_sha256'][name]:raise ValueError(f'Changed result {file}')
    SOURCES[str(file.relative_to(ROOT)).replace('\\','/')]=digest
    return pd.read_csv(file)

def paired(table,left,right,protocol='cluster',metric='pcc'):
    f=table[(table.protocol==protocol)&(table.metric==metric)]
    x=f[(f.left_mode==left)&(f.right_mode==right)]
    if len(x):
        r=x.iloc[0];return [float(r.mean_difference),float(r.ci95_low),float(r.ci95_high)]
    r=f[(f.left_mode==right)&(f.right_mode==left)].iloc[0]
    return [-float(r.mean_difference),-float(r.ci95_high),-float(r.ci95_low)]

def ci(values,signed=False):
    if not np.isfinite(values).all():raise ValueError('A nonfinite interval cannot support a manuscript claim')
    m,l,h=values
    return f'{m:+.4f} [{l:+.4f}, {h:+.4f}]' if signed else f'{m:.3f} [{l:.3f}, {h:.3f}]'

def rowmetric(r):return [float(r.mean_pcc),float(r.pcc_ci95_low),float(r.pcc_ci95_high)]

def sci(value):
    mantissa,exponent=f'{value:.2e}'.split('e')
    return mantissa+r'\times10^{'+str(int(exponent))+'}'

def write(name,text):
    # Allow prose to wrap between an estimate and its interval; table cells stay intact.
    text=re.sub(r'\$([+-]\d+\.\d+) (\[[^$]+\])\$',lambda m:'$'+m[1]+r'$ (95\% CI $'+m[2]+'$)',text)
    text=text.replace(r'\begin{table}', '\n\n'+r'\begin{table}').replace(r'\end{table}',r'\end{table}'+'\n\n')
    (PAPER/name).write_text('% Generated by scripts/summarize_study.py; do not transcribe historical metrics here.\n'+text+'\n',encoding='utf-8')

def core_results():
    s=read('core','summary.csv');p=read('core','paired_differences.csv');per=read('core','per_protein.csv')
    rows={m:s[(s.protocol=='cluster')&(s['mode']==m)].iloc[0] for m in LABELS}
    delta=paired(p,'graph','graph+center0');cfg=json.loads((STUDY/'dataset/dataset_config.json').read_text())
    NUMBERS['dataset']={k:cfg[k] for k in ('n_proteins','n_residues','n_clusters')}
    NUMBERS['core']=s.to_dict('records');NUMBERS['primary_delta']=delta
    macros={'StudyProteins':str(cfg['n_proteins']),'StudyResidues':f"{cfg['n_residues']:,}",'StudyClusters':str(cfg['n_clusters']),
      'GraphPCC':f"{rows['graph'].mean_pcc:.3f}",'NativePCC':f"{rows['native0'].mean_pcc:.3f}",
      'NativeGraphPCC':f"{rows['graph+native0'].mean_pcc:.3f}",'CenterPCC':f"{rows['center0'].mean_pcc:.3f}",
      'CombinedPCC':f"{rows['graph+center0'].mean_pcc:.3f}",'CombinedCILow':f"{rows['graph+center0'].pcc_ci95_low:.3f}",
      'CombinedCIHigh':f"{rows['graph+center0'].pcc_ci95_high:.3f}",
      **{k:f'{v:+.4f}' for k,v in zip(('DeltaPCC','DeltaCILow','DeltaCIHigh'),delta)}}
    abstract=(r'The graph baseline attained mean per-protein correlation $'+macros['GraphPCC']+
      r'$, while adding corrected center-zero degree-zero spectra yielded $'+macros['CombinedPCC']+
      r'$ (paired difference $'+macros['DeltaPCC']+r'$; 95\% cluster-bootstrap interval $['+macros['DeltaCILow']+','+macros['DeltaCIHigh']+r']$).')
    if delta[1]<=0<=delta[2]:abstract+=' The primary comparison does not resolve an improvement in mean correlation under this evaluation.'
    macros['AbstractEmpiricalResults']=abstract
    write('generated_results.tex','\n'.join('\\newcommand{\\'+k+'}{'+v+'}' for k,v in macros.items()))
    text=r'''\subsection{Core held-out comparison}
The final cohort contains \StudyProteins\ structures, \StudyResidues\ retained residues, and \StudyClusters\ sequence components. Every core model uses this same cohort and its frozen folds. Table~\ref{tab:core} reports the mean of within-protein metrics, rather than treating all residues as independent examples in the performance summary.
\begin{table}[htbp]\centering\small
\caption{Core sequence-controlled evaluation. Brackets are 95\% cluster-bootstrap intervals for mean protein PCC, conditional on the fitted models and fixed folds. Spearman and normalized RMSE are likewise averaged across proteins.}
\label{tab:core}
\begin{tabular}{lrrr}\toprule
Representation & PCC [95\% CI] & Spearman & RMSE$_z$\\\midrule
'''
    for mode,r in rows.items():text+=f'{LABELS[mode]} & {ci(rowmetric(r))} & {r.mean_spearman:.3f} & {r.mean_rmse_z:.3f} '+r'\\'+'\n'
    text+=r'\bottomrule\end{tabular}\end{table}'+'\n'
    native=paired(p,'graph','graph+native0');ident=paired(p,'graph','graph+identity0');geom=paired(p,'graph','graph+geometric0')
    text+=f'The prespecified graph-plus-center-zero comparison gives a mean paired PCC change of ${ci(delta,True)}$. '
    text+=('This interval crosses zero; the experiment does not resolve a mean improvement under this evaluation at this uncertainty level. ' if delta[1]<=0<=delta[2] else ('The conditional interval is entirely positive, supporting an incremental predictive contribution under this fixed protocol. ' if delta[1]>0 else 'The conditional interval is entirely negative, indicating that this addition reduced mean predictive correlation under the fixed protocol. '))
    text+=f'For comparison, adding legacy graph spectra changes PCC by ${ci(native,True)}$; the identity and all-one geometric sheaf additions change it by ${ci(ident,True)}$ and ${ci(geom,True)}$, respectively. These are paired changes on the same structures; they are not estimates of representation independence.\n\n'
    pivot=per[per.protocol=='cluster'].pivot(index='protein_id',columns='mode',values='pcc');d=(pivot['graph+center0']-pivot['graph']).dropna()
    sens=paired(p,'graph','graph+center0','protein')
    NUMBERS['improved_proteins']=int((d>0).sum());NUMBERS['primary_valid_pairs']=len(d);NUMBERS['sensitivity_delta']=sens
    text+=f'The center-zero addition improves PCC in {int((d>0).sum())} of {len(d)} evaluable proteins; the individual changes are shown in Figure~\\ref{{fig:performance}}. Protein-only folds give a paired change of ${ci(sens,True)}$. The sensitivity analysis changes the grouping protocol while keeping model settings fixed; it is not a second independent dataset. All pairwise metric differences, valid-protein counts, pooled diagnostics, and per-protein values are released. Neither the confidence intervals nor the number of favorable comparisons accounts for a broad search over representations; the experiment uses the declared finite set.\n'
    validation=json.loads((STUDY/'operator_validation.json').read_text())
    if validation['status']!='passed':raise ValueError('Operator validation has not passed')
    SOURCES['results/study/operator_validation.json']=sha256_file(STUDY/'operator_validation.json')
    NUMBERS['operator_validation']={'counts':validation['counts'],'metrics':validation['metrics']}
    c=validation['counts'];v=validation['metrics']
    numerical=(f'The seeded numerical report contains {c["persistent_operators"]} persistent operators across {c["clouds"]} coordinate clouds, including {c["random_clouds"]} random general-position clouds. '
        f'The largest absolute Schur-versus-independent-nullspace matrix discrepancy is ${sci(v["schur_vs_independent_nullspace"]["max_absolute_error"])}$, '
        f'and the largest consecutive-coboundary residual is ${sci(v["D1_D0"]["max_absolute_error"])}$. '
        'Every tested persistent nullity equals the independently computed cohomology-restriction rank. The square-cycle example changes from ordinary nullity one to persistent nullity zero as its filling enters. These finite checks support the implementation and accompany the analytic arguments; they do not replace those arguments.\n\n')
    write('generated_main_results.tex',numerical+text)

def persistence_results():
    s=read('d1','summary.csv');pairs=read('d1','paired_differences.csv')
    NUMBERS['degree1']=s.to_dict('records');deltas={};lower_deltas={}
    text=r'''\subsection{Degree-one persistence and scale controls}
Degree-one features and all matched comparators completed on the full audited cohort. Table~\ref{tab:persistence} compares each addition with the graph-plus-degree-zero model using the same sheaf construction. Lower-endpoint, upper-endpoint, and persistent additions each supply twelve spectral summaries, so their feature counts match.
\begin{table}[htbp]\centering\small
\caption{Matched degree-one additions under sequence-controlled folds. The changes are paired mean per-protein PCC differences from the corresponding graph-plus-degree-zero model.}
\label{tab:persistence}
\begin{tabular}{llrr}\toprule
Sheaf & Degree-one addition & Mean PCC & Paired change [95\% CI]\\\midrule
'''
    for kind,label in [('identity','Identity'),('geometric','Geometric'),('center','Center-zero')]:
        base=f'graph+{kind}0'
        for suffix,addition in [('1','Ordinary lower'),('_upper1','Ordinary upper'),('_p1','Persistent')]:
            mode=base+'+'+kind+suffix;r=s[s['mode']==mode].iloc[0];diff=paired(pairs,base,mode)
            text+=f'{label} & {addition} & {r.mean_pcc:.3f} & {ci(diff,True)} '+r'\\'+'\n'
        deltas[kind]=paired(pairs,base+'+'+kind+'_upper1',base+'+'+kind+'_p1')
        lower_deltas[kind]=paired(pairs,base+'+'+kind+'1',base+'+'+kind+'_p1')
    text+=r'\bottomrule\end{tabular}\end{table}'+'\n'
    text+='The persistent-minus-upper-ordinary comparisons are '+', '.join(f'${ci(v,True)}$ ({k.replace("center","center-zero")})' for k,v in deltas.items())+'. '
    text+='These comparisons isolate the value of the constrained two-scale operator from the simpler alternative of accessing the larger filtration radius. The point estimates describe predictive effects of the summarized spectra; the operators can differ algebraically even when their predictive performances are close.\n\n'
    NUMBERS['persistent_vs_upper']=deltas
    NUMBERS['persistent_vs_lower']=lower_deltas
    characterization=pd.read_csv(STUDY/'feature_characterization.csv')
    audit=json.loads((STUDY/'feature_characterization.json').read_text())
    if audit['status']!='complete' or not (characterization.n_neighborhoods==int(s.n_residues.iloc[0])).all():raise ValueError('Feature characterization does not match evaluated neighborhoods')
    source(STUDY/'feature_characterization.csv');source(STUDY/'feature_characterization.json')
    NUMBERS['feature_characterization']=characterization.to_dict('records')
    identity=characterization[(characterization.construction=='identity')&(characterization.kind=='persistent')].sort_values('lower_radius_angstrom')
    fractions=identity.fraction_nonzero.to_numpy()*100
    different=[100*r[f'fraction_positive_summaries_differ_from_{endpoint}'] for r in audit['degree1_endpoint_comparisons'] for endpoint in ('lower','upper')]
    NUMBERS['positive_summary_difference_percent_range']=[min(different),max(different)]
    text+=f'The descriptor audit confirms that persistence changes the represented information. Identity and all-one geometric restrictions have identical numerical nullities at every tested neighborhood and scale, as expected from the invertible gauge. For the identity sheaf, persistent degree-one nullity is nonzero in {fractions[0]:.2f}\\% of neighborhoods for $(3,4)$ and {fractions[1]:.3f}\\% for $(5,6)$. These descriptive frequencies weight all retained residue-centered neighborhoods equally; they are not protein-level prediction statistics. The supplement reports both endpoint counts and center-zero counts.\n\n'
    text+=f'Across the three sheaves, two scale pairs, and two endpoint comparisons, the five positive-spectrum summary vectors differ in {min(different):.2f}--{max(different):.2f}\\% of neighborhoods (relative tolerance $10^{{-8}}$, absolute tolerance $10^{{-10}}$). This compares stored summaries, not full matrices of potentially different dimensions; equal summary vectors would not establish spectral equivalence.\n\n'
    core=read('core','per_protein.csv');base=core[(core.protocol=='cluster')&(core['mode']=='graph+center0')]
    abl=[]
    for name in ('nullity','positive','a3','a4','a5','a6'):
        row=read('ablation_'+name,'summary.csv').iloc[0];per=read('ablation_'+name,'per_protein.csv')
        joined=base.merge(per,on='protein_id',suffixes=('_full','_ablation'),validate='one_to_one')
        if len(joined)!=len(base) or len(joined)!=len(per):raise ValueError('Ablation cohort mismatch')
        if not (joined.cluster_id_full==joined.cluster_id_ablation).all() or not (joined.fold_full==joined.fold_ablation).all():raise ValueError('Ablation partitions differ')
        diff=cluster_bootstrap((joined.pcc_ablation-joined.pcc_full).to_numpy(),joined.cluster_id_full.to_numpy())
        abl.append({'ablation':name,'pcc':float(row.mean_pcc),'pcc_ci_low':float(row.pcc_ci95_low),'pcc_ci_high':float(row.pcc_ci95_high),'difference_from_full':[float(x) for x in diff],
                    'mean_spearman':float(row.mean_spearman),'mean_rmse_z':float(row.mean_rmse_z)})
    NUMBERS['ablations']=abl
    a={r['ablation']:r for r in abl}
    text+=f'For the graph-plus-center-zero degree-zero model, retaining only nullities gives mean PCC {a["nullity"]["pcc"]:.3f}, while retaining only positive-spectrum summaries gives {a["positive"]["pcc"]:.3f}. '
    text+='Single-scale models at radii 3, 4, 5, and 6 '+r'\AA\ give '+', '.join(f'{a[f"a{r}"]["pcc"]:.3f}' for r in (3,4,5,6))+', respectively. These fixed ablations retain the graph features; they do not attribute a causal effect to topology or identify an optimal radius. The complete intervals and paired changes are included in the supplement.\n\n'
    costs={name:float(pd.read_csv(STUDY/name).seconds.sum())/60 for name in ('d0_timing.csv','d1_timing.csv','upper_timing.csv')}
    for name in costs:source(STUDY/name)
    NUMBERS['feature_worker_minutes']=costs
    text+=f'The initial degree-zero pass used {costs["d0_timing.csv"]:.1f} summed worker minutes; the degree-one addition used {costs["d1_timing.csv"]:.1f}, and the added upper-endpoint controls used {costs["upper_timing.csv"]:.1f}. Four feature workers were used. The initial pass preceded the modified-residue amendment, so the degree-one timing also includes recalculation of degree-zero features for the 24 affected structures. These measured costs include matrix construction and spectral summarization, and are distinct from model-fitting time.\n'
    write('generated_persistence_results.tex',text)
    supp=r'''
\begin{table}[htbp]\centering\small
\caption{Degree-zero ablations of graph plus center-zero features. All models keep all graph features. The paired change is relative to the full multiscale spectral representation.}
\begin{tabular}{lrr}\toprule
Spectral summaries retained & Mean PCC [95\% CI] & Paired change [95\% CI]\\\midrule
'''
    for row in abl:
        label={'nullity':'Nullities only','positive':'Positive spectra only'}.get(row['ablation'],'Radius '+row['ablation'][1:]+r'\,\AA')
        supp+=f'{label} & {ci([row["pcc"],row["pcc_ci_low"],row["pcc_ci_high"]])} & {ci(row["difference_from_full"],True)} '+r'\\'+'\n'
    supp+=r'\bottomrule\end{tabular}\end{table}'+'\n'
    supp+=r'''\begin{table}[htbp]\centering\small
\caption{Persistent-minus-static degree-one comparisons. All additions use twelve features on the same graph-plus-degree-zero baseline. Intervals are paired cluster-bootstrap intervals for mean protein PCC.}
\begin{tabular}{llr}\toprule
Sheaf & Static comparator & Paired PCC change [95\% CI]\\\midrule
'''
    for kind,label in [('identity','Identity'),('geometric','Geometric'),('center','Center-zero')]:
        for endpoint,values in [('Lower',lower_deltas[kind]),('Upper',deltas[kind])]:
            supp+=f'{label} & {endpoint} & {ci(values,True)} '+r'\\'+'\n'
    supp+=r'\bottomrule\end{tabular}\end{table}'+'\n'
    supp+=r'''\begin{table}[htbp]\centering\small
\caption{Nonzero degree-one kernel frequencies across all 78,400 residue-centered neighborhoods. Neighborhoods are weighted equally. Identity and geometric nullities agree exactly at all evaluated scales. Equal endpoints describe the corresponding sheaf cohomology; unequal endpoints describe its persistent cohomology restriction rank.}
\begin{tabular}{lrrrr}\toprule
Radius pair (\AA) & \shortstack{Identity\\nonzero (\%)} & \shortstack{Center-zero\\nonzero (\%)} & \shortstack{Mean identity\\nullity} & \shortstack{Mean center\\nullity}\\\midrule
'''
    for a,b in ((3,3),(4,4),(5,5),(6,6),(3,4),(5,6)):
        f=characterization[(characterization.degree==1)&(characterization.lower_radius_angstrom==a)&(characterization.upper_radius_angstrom==b)]
        i=f[f.construction=='identity'].iloc[0];c=f[f.construction=='center'].iloc[0]
        supp+=f'$({a},{b})$ & {100*i.fraction_nonzero:.3f} & {100*c.fraction_nonzero:.3f} & {i.mean_nullity:.3f} & {c.mean_nullity:.3f} '+r'\\'+'\n'
    supp+=r'\bottomrule\end{tabular}\end{table}'+'\n'
    ordinary=read('core','summary.csv');ordinary=ordinary[ordinary.protocol=='protein']
    supp+=r'''\begin{table}[htbp]\centering\small
\caption{Protein-only split sensitivity analysis on the same 364 structures.}
\begin{tabular}{lrrr}\toprule
Representation & PCC [95\% CI] & Spearman & RMSE$_z$\\\midrule
'''
    for mode in LABELS:
        r=ordinary[ordinary['mode']==mode].iloc[0];supp+=f'{LABELS[mode]} & {ci(rowmetric(r))} & {r.mean_spearman:.3f} & {r.mean_rmse_z:.3f} '+r'\\'+'\n'
    supp+=r'\bottomrule\end{tabular}\end{table}'+'\n'
    write('generated_supplement_results.tex',supp)

def check_case_inputs(pid,render=False):
    a=json.loads((STUDY/f'cases/{pid}_provenance.json').read_text())
    check=a['main_prediction_check']
    if check.get('status')!='verified' or check['sha256']!=sha256_file(STUDY/'core/predictions.csv.gz'):
        raise ValueError(f'{pid}: case not verified against current held-out predictions')
    for suffix,digest in a['output_sha256'].items():
        if source(STUDY/f'cases/{pid}_{suffix}')!=digest:raise ValueError(f'{pid}: changed case output {suffix}')
    source(STUDY/f'cases/{pid}_provenance.json')
    if render:
        for item in a['rendering'].values():
            if source(ROOT/item['path'])!=item['sha256']:raise ValueError(f'{pid}: changed molecular rendering')
    return a

def case_results():
    per=read('core','per_protein.csv');cases=[]
    for pid in ('1ULR','1X3O'):
        a=check_case_inputs(pid)
        row=per[(per.protocol=='cluster')&(per['mode']=='graph+center0')&(per.protein_id==pid)].iloc[0]
        cases.append({'protein_id':pid,'pcc':float(row.pcc),'spearman':float(row.spearman),'rmse_z':float(row.rmse_z),'expected_value':a['expected_value'],'additivity_max_error':a['additivity_max_error'],'n_residues':a['n_residues']})
    NUMBERS['cases']=cases
    text=r'\subsection{Prespecified protein cases}'+'\n'
    text+=f'The principal case 1ULR has {cases[0]["n_residues"]} mapped residues, held-out PCC {cases[0]["pcc"]:.3f}, Spearman correlation {cases[0]["spearman"]:.3f}, and normalized RMSE {cases[0]["rmse_z"]:.3f}. The companion 1X3O has {cases[1]["n_residues"]} mapped residues, PCC {cases[1]["pcc"]:.3f}, Spearman correlation {cases[1]["spearman"]:.3f}, and normalized RMSE {cases[1]["rmse_z"]:.3f}. Both cases retain their prespecified selection regardless of score. The observed and predicted ribbon colors share the same symmetric scale; signed sheaf contributions use their own stated scale.\n\n'
    maxerr=max(c['additivity_max_error'] for c in cases)
    text+=f'The maximum absolute SHAP reconstruction error across the two cases is ${sci(maxerr)}$ in target z units. The released tables contain all 37 feature attributions per residue, the training-only backgrounds, and model identities. The sheaf-group subtotal shown in Figure~\\ref{{fig:protein}} excludes the graph-feature contribution and the baseline expectation. Consequently its spatial pattern describes this feature group\'s use by the held-out model, rather than repeating the entire prediction or identifying the influence of neighboring residues.\n'
    write('generated_case_results.tex',text)

def main():
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--core-only',action='store_true');args=p.parse_args()
    core_results()
    if not args.core_only:persistence_results();case_results()
    (STUDY/'report_numbers.json').write_text(json.dumps({'numbers':NUMBERS,'source_sha256':SOURCES,'generator_sha256':sha256_file(Path(__file__))},indent=2)+'\n')

if __name__=='__main__':main()
