"""Build the integrated article without modifying the frozen analysis outputs."""

import argparse
from pathlib import Path
import subprocess


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--tectonic", default="tectonic")
    args = parser.parse_args()
    paper = Path(__file__).resolve().parent
    text = (paper / "generated_persistence_results.tex").read_text(encoding="utf-8")
    replacements = {
        "The supplement reports": "The detailed comparison tables below report",
        "included in the supplement.": "included in the detailed comparison tables below.",
        ") (identity),": ") for identity;",
        ") (geometric),": ") for geometric;",
        ") (center-zero).": ") for center-zero.",
    }
    for old, new in replacements.items():
        if text.count(old) != 1:
            raise ValueError(f"Expected one editorial replacement for {old!r}")
        text = text.replace(old, new)
    # Permit a line break inside the long inline confidence intervals.
    text = text.replace(", +0.", ",\\allowbreak +0.")
    start = text.index("The persistent-minus-upper-ordinary comparisons")
    end = text.index("\n\n", start)
    text = text[:start] + "\\begin{samepage}\n" + text[start:end] + "\n\\par\\end{samepage}" + text[end:]
    target = paper / "sections" / "persistence_results_integrated.tex"
    target.write_text(
        "% Generated by paper/build.py; numerical source remains unchanged.\n" + text,
        encoding="utf-8", newline="\n",
    )
    subprocess.run(
        [args.tectonic, "-X", "compile", "paper/manuscript.tex", "--keep-logs"],
        cwd=paper.parent, check=True,
    )


if __name__ == "__main__":
    main()
