"""Build the integrated article without modifying the frozen analysis outputs."""

import argparse
import json
from pathlib import Path
import re
import subprocess


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--tectonic", default="tectonic")
    args = parser.parse_args()
    paper = Path(__file__).resolve().parent
    edits = json.loads((paper / "editorial_replacements.json").read_text(encoding="utf-8"))
    for filename, replacements in edits.items():
        original = (paper / filename).read_text(encoding="utf-8")
        text = original
        for old, new in replacements:
            if text.count(old) != 1:
                raise ValueError(f"Expected one editorial replacement in {filename}: {old!r}")
            text = text.replace(old, new)
        if re.findall(r"[-+]?\d+(?:\.\d+)?", original) != re.findall(r"[-+]?\d+(?:\.\d+)?", text):
            raise ValueError(f"Editorial changes altered numerical tokens in {filename}")
        if filename == "generated_persistence_results.tex":
            text = text.replace(", +0.", ",\\allowbreak +0.")
            for opening in (
                "The persistent-minus-upper-ordinary comparisons",
                "The descriptor audit confirms",
            ):
                start = text.index(opening)
                end = text.index("\n\n", start)
                text = text[:start] + "\\begin{samepage}\n" + text[start:end] + "\n\\par\\end{samepage}" + text[end:]
        name = Path(filename).stem.removeprefix("generated_") + "_integrated.tex"
        (paper / "sections" / name).write_text(
            "% Generated by paper/build.py; numerical source remains unchanged.\n" + text,
            encoding="utf-8", newline="\n",
        )
    subprocess.run(
        [args.tectonic, "-X", "compile", "paper/manuscript.tex", "--keep-logs"],
        cwd=paper.parent, check=True,
    )


if __name__ == "__main__":
    main()
